# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WMGameProxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  

  target 'WMGameProxyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WMGameProxyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
